language: objective-c
install: script/bootstrap
xcode_workspace: FMWKTemplate.xcworkspace
env:
  global:
    - XCTOOL_OPTIONS="-configuration Test"
  matrix:
    - SCHEME=FMWKTemplate-Mac
    # - SCHEME=FMWKTemplate-iOS
script: script/cibuild $SCHEME
