language: objective-c
install: script/bootstrap
xcode_workspace: ECLibrary.xcworkspace
env:
  global:
    - XCTOOL_OPTIONS="-configuration Test"
  matrix:
    - SCHEME=ECLibrary-Mac
    # - SCHEME=ECLibrary-iOS
script: script/cibuild $SCHEME
